links:
  - text: 'マスクについて'
    href: '/?page=top'
  - text: '家庭用マスク'
    href: '/?post' 
  - text: '捨て方'
    href: './'
    sublinks:
    - text: '方法'
      href: 'http://test.usptomo.com'
    - text: '環境'
      href: 'https://b.ueda.tech/'
